---
application:
  name: "helperscript"
  project: "CrazyBotsz"
  organization: "QoveryCommunity"
  storage:
  - name: "app"
    size: "200"
    type: "fast_ssd"
    mount_point: "/mnt/app"
  - name: "app2"
    size: "200"
    type: "fast_ssd"
    mount_point: "/mnt/app2"
routers:
- name: "main-helperscript"
  routes:
  - application_name: "helperscript"
    paths:
    - "/*"
